esphome:
  name: xiao-ir-mate
  friendly_name: XIAO Smart IR Mate
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:
  id: api_id
  encryption:   # Uses key set by Home Assistant

ota:
  - platform: esphome
    id: ota_esphome

wifi:
  # Set up a wifi access point using the device name above
  ap:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

network:
  enable_ipv6: true

button:
  - platform: factory_reset
    id: factory_reset_button
    name: "Factory Reset"
    entity_category: diagnostic
    internal: true
  - platform: restart
    id: restart_button
    name: "Restart"
    entity_category: config
    disabled_by_default: true
    icon: "mdi:restart"

remote_transmitter:
  id: ir_tx
  pin: GPIO3
  carrier_duty_percent: 50%

remote_receiver:
  - id: ir_rx
    pin:
      number: GPIO4
      inverted: true

infrared:
  # IR transmitter instance
  - platform: ir_rf_proxy
    name: IR Proxy Transmitter
    id: ir_proxy_tx
    remote_transmitter_id: ir_tx
  # IR receiver instance
  - platform: ir_rf_proxy
    name: IR Proxy Receiver
    id: ir_proxy_rx
    remote_receiver_id: ir_rx
